reload: "&b[&fFreeze&b] &aPlugin újraindítva!"
noPerm: "&b[&fFreeze&b] &cNincs jogod ehhez!"
console: "&b[&fFreeze&b] &cCsak játékosok által használható!"
freezeStaff: "&b[&fFreeze&b] &9Játékos sikeresen lefagyasztva!"
freezePlayer: "&b[&fFreeze&b] &9Le lettél fagyasztva! \n&l&43 &cperced van elküldeni az AnyDesk kódod! \n&4https://anydesk.com/en"
unfreezeStaff: "&b[&fFreeze&b] &9Játékos kifagyasztva!"
unfreezePlayer: "&b[&fFreeze&b] &9Ki lettél fagyasztva!"
noSubject: "&b[&fFreeze&b] &cNevezz meg egy játékost!"
moreSubjects: "&b[&fFreeze&b] &cCsak egy játékost nevezz meg!"
unknownSubject: "&b[&fFreeze&b] &cNem található játékos ilyen névvel!"
selfCmd: "&b[&fFreeze&b] &cMagadat nem fagyaszthatod le!"
staff: "&a&lStaff &a|| "
player: "&c&lJátékos &c|| "
quitban: " &c kilépett! KATTINTS IDE a kitiltáshoz!"
quitbc: " &c kilépett ss közben!"
alreadyFrozen: "&b[&fFreeze&b] &cEz a játékos már le van fagyasztva!"
frozenByOther: "&b[&fFreeze&b] &cEzt a játékost már más lefagyasztotta!"
notFrozen: "&b[&fFreeze&b] &cEz a játékos nincs lefagyasztva!"